server:
  port: 80
spring:
  datasource:
    url: jdbc:oracle:thin://${ORACLE_HOST}:${ORACLE_PORT:5432}/${ORACLE_DB}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    locations: classpath:db/migration
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

